"""
Interview Video Analyzer
Uploads a video to Gemini, runs analysis, returns a Markdown report.
"""

import time
from datetime import datetime

from google import genai
from google.genai import types

SUPPORTED_MIME = {
    "mp4":  "video/mp4",
    "mov":  "video/quicktime",
    "avi":  "video/x-msvideo",
    "mkv":  "video/x-matroska",
    "webm": "video/webm",
    "flv":  "video/x-flv",
    "mpeg": "video/mpeg",
    "mpg":  "video/mpeg",
}

ANALYSIS_PROMPT = """\
You are an expert interview coach with deep experience evaluating candidates \
across behavioral, technical, and coding interviews.

Analyze this interview video thoroughly and produce a detailed feedback report \
in Markdown format.

---

## WHAT TO ANALYZE

### 1. Body Language & Posture
- Posture (upright vs slouched, leaning in vs back)
- Hand gestures (purposeful vs distracting vs absent)
- Fidgeting, nervous habits, self-touching
- Head nodding and active listening signals
- Overall physical presence and confidence

### 2. Eye Contact
- Eye contact with camera/interviewer (consistent, occasional, avoidant)
- Looking away when thinking vs looking away due to nerves
- Reading from notes or screen too often

### 3. Facial Expressions
- Genuine vs forced smiles
- Signs of nervousness or discomfort
- Expressiveness and engagement
- Resting expression during listening

### 4. Speech Patterns
- Pace (too fast, too slow, appropriate)
- Filler words (um, uh, like, you know — count approximate frequency)
- Clarity and articulation
- Volume and projection
- Pausing (strategic pauses vs dead silence from uncertainty)
- Vocal variety vs monotone delivery

### 5. Speech Content & Answer Quality
- Answer structure (clear beginning, middle, end)
- Use of STAR method or other frameworks where appropriate
- Conciseness vs rambling
- Specificity (concrete examples vs vague generalities)
- Relevance to the question asked
- Confidence in content delivery
- Handling of difficult or unexpected questions

### 6. Overall Interview Presence
- First impression and energy level
- Enthusiasm and genuine interest
- Professional appropriateness
- Rapport building with interviewer
- Recovery from mistakes or stumbles

### 7. Coding Interview (only if this is a coding interview)
- Extract the exact coding question(s) asked
- Summarize the solution the candidate provided
- Evaluate: did they clarify constraints before coding?
- Evaluate: did they think out loud and explain their reasoning?
- Evaluate: correctness of the solution
- Evaluate: time/space complexity awareness
- Evaluate: code quality and cleanliness
- Evaluate: how they handled edge cases
- Evaluate: how they responded to hints or follow-up questions

---

## REPORT FORMAT

Produce the report in this exact structure:

# Interview Performance Report
**Date analyzed:** {date}
**Company:** [company name detected from video — logos, email domains, interviewer intro, screen content, etc. Write "Unknown" if not detectable]
**Interview type:** [Behavioral / Technical / Coding / General — detect from video]
**Overall rating:** [X/10]

---

## Executive Summary
[3-5 sentence summary of overall performance]

---

## What You Did Well ✓
[Bullet list of specific strengths with timestamps where possible]

---

## What Needs Improvement ✗
[Bullet list of specific weaknesses with timestamps where possible]

---

## Detailed Breakdown

### Body Language & Posture
**Score: X/10**
[Detailed feedback]

### Eye Contact
**Score: X/10**
[Detailed feedback]

### Facial Expressions
**Score: X/10**
[Detailed feedback]

### Speech Patterns
**Score: X/10**
[Detailed feedback — include approximate filler word count/frequency]

### Speech Content & Answer Quality
**Score: X/10**
[Detailed feedback per answer/question if multiple questions asked]

### Overall Presence
**Score: X/10**
[Detailed feedback]

---

## Coding Interview Details
*(Include this section only if this is a coding interview — skip entirely otherwise)*

### Question Asked
[Exact or reconstructed question from the video]

### Candidate's Solution
[Description or pseudocode of the solution provided]

### Solution Evaluation
- **Correctness:** [correct / partially correct / incorrect — explain]
- **Approach:** [brute force / optimal / near-optimal]
- **Time complexity:** [what candidate said vs actual]
- **Space complexity:** [what candidate said vs actual]
- **Edge cases handled:** [yes / partially / no — which ones]
- **Communication while coding:** [strong / adequate / weak]

---

## Top 5 Priority Improvements
1.
2.
3.
4.
5.

---

## Action Plan
[Concrete, specific exercises or practices for each priority improvement]

---
*Report generated by Interview Prep Generator — Video Analyzer*
""".format(date=datetime.now().strftime("%B %d, %Y"))


def get_mime(filename: str) -> str | None:
    ext = filename.rsplit(".", 1)[-1].lower()
    return SUPPORTED_MIME.get(ext)


def analyze_video(
    client: genai.Client,
    video_path: str,
    filename: str,
    model: str = "gemini-2.0-flash",
    status_callback=None,
) -> str:
    """
    Upload a video file to Gemini by path, run analysis, return Markdown report string.
    status_callback(msg) is called with progress updates if provided.
    """
    def log(msg):
        if status_callback:
            status_callback(msg)

    mime = get_mime(filename)
    if not mime:
        ext = filename.rsplit(".", 1)[-1].lower()
        raise ValueError(f"Unsupported video format: .{ext}. Supported: {', '.join(SUPPORTED_MIME)}")

    log("Uploading video to Gemini...")
    with open(video_path, "rb") as f:
        video_file = client.files.upload(
            file=f,
            config=types.UploadFileConfig(mime_type=mime, display_name=filename),
        )

    log("Waiting for Gemini to process the video...")
    while video_file.state.name == "PROCESSING":
        time.sleep(3)
        video_file = client.files.get(name=video_file.name)

    if video_file.state.name == "FAILED":
        raise RuntimeError(f"Gemini video processing failed: {video_file.state}")

    log(f"Analyzing with {model}... (this may take 1–3 minutes)")
    response = client.models.generate_content(
        model=model,
        contents=[
            types.Part.from_uri(file_uri=video_file.uri, mime_type=mime),
            ANALYSIS_PROMPT,
        ],
        config=types.GenerateContentConfig(
            temperature=0.3,
            max_output_tokens=8192,
        ),
    )

    # Clean up file from Gemini servers
    try:
        client.files.delete(name=video_file.name)
    except Exception:
        pass

    log("Analysis complete.")
    return response.text
